### ISSUE TITLE
Model requires 6 inputs. Input Feed contains 2

### ISSUE THREAD

**Issue by v-yunbin** [RapidAI/RapidASR#2] opened 2022-07-14 05:03 UTC
export onnx model with “wenet/bin/export_onnx.py” and  run “python test_demo.py” with exported  onnx ， get follow error：
```
Traceback (most recent call last):
  File "test_demo.py", line 4, in <module>
    from wenet import WenetInfer
  File "/data/disk1/ybZhang/.opendir/RapidASR/python/base_wenet/wenet/__init__.py", line 2, in <module>
    from .wenet_infer import WenetInfer
  File "/data/disk1/ybZhang/.opendir/RapidASR/python/base_wenet/wenet/wenet_infer.py", line 37, in <module>
    from swig_decoders import (PathTrie, TrieVector,
ModuleNotFoundError: No module named 'swig_decoders'
source activate wenet
(wenet) [ybZhang@master /data/disk1/ybZhang/.opendir/RapidASR/python/base_wenet]$python test_demo.py pretrain_model2/onnx_cpu/ test_data/test.wav
Traceback (most recent call last):
  File "test_demo.py", line 22, in <module>
    key, content, elapse = wenet_infer(wav_path)
  File "/data/disk1/ybZhang/.opendir/RapidASR/python/base_wenet/wenet/wenet_infer.py", line 148, in __call__
    ort_outs = self.encoder_ort_session.run(None, ort_inputs)
  File "/home/ybZhang/miniconda3/envs/wenet/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 184, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 6 inputs. Input Feed contains 2
```

**Comment by SWHL** [comment] 2022-07-14 05:53
- I can't reproduce the error in my pc (linux CentOS).
- This erros may be caused that the swig_decoders package doesn't not install correctly.
- Please make sure this swig_decoders package is installed correctly.

**Comment by v-yunbin** [comment] 2022-07-14 08:40
installed the swig_decoders  and I run “python test_demo.py” with onnx model downloaded from "https://github.com/RapidAI/RapidASR/tree/main/python/base_wenet" and  it worked.

**Comment by SWHL** [comment] 2022-07-14 08:43
- OK, has this problem been resolved?
- If yes, please close the issue.

**Comment by v-yunbin** [comment] 2022-07-14 08:46
> * OK, has this problem been resolved?
> * If yes, please close the issue.

Not solved, i means that downloading your onnx model it worked but use my exported onnx model, it met above error：
```
Traceback (most recent call last):
  File "test_demo.py", line 22, in <module>
    key, content, elapse = wenet_infer(wav_path)
  File "/data/disk1/ybZhang/.opendir/RapidASR/python/base_wenet/wenet/wenet_infer.py", line 148, in __call__
    ort_outs = self.encoder_ort_session.run(None, ort_inputs)
  File "/home/ybZhang/miniconda3/envs/wenet/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 184, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
```

**Comment by SWHL** [comment] 2022-07-14 10:21
Please make sure your trained model has the same configuration with [this](https://github.com/wenet-e2e/wenet/blob/a92952827c/examples/aishell/s0/conf/train_conformer.yaml).
Because the inference code is derived from this configuration.

**Comment by SWHL** [comment] 2022-08-17 08:31
- When I train the other speech model, I met the same problem with the inference code.
- Solution:
    -  Visualize the model with the [netron](https://netron.app/)
    -  Click the input node, look the right borard and check the inputs nums.

**Closed** 2023-02-14 05:50 UTC
